services:
  nginx: 
    restart: always
    image: nginx:stable-alpine
    ports: 
      - ${PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  crud-node-app:
    restart: always
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: crud-node-app
    host_name: crud-node-app
    env_file:
      - ./.env
    
    depends_on: 
      - mongo
      - redis
      - nginx
      
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/mongodb
    
    env_file:
      - ./.env

  redis: 
    image: redis
    restart: always

volumes: 
  mongo-db:
    name: mongodb-data
