version: "3"
services:
  nginx: 
    image: nginx:stable-alpine

  crud-node-app:
    build: 
      context: .
    
    environment:
      - NODE_ENV=development
      - MONGO_DB_URL=${MONGO_DB_DEV_URL}

    command: npm run dev
