version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - ${PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - crud-node-app 

  crud-node-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    
    volumes:
      - ./:/app
      - /app/node_modules
    
    environment:
      - NODE_ENV=development
      - MONGO_DB_URL=${MONGO_DB_DEV_URL}

    env_file:
      - ./.env
    
    command: npm run dev
