version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - ${PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - crud-node-app

  crud-node-app:
    restart: always
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on: 
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=meowmeow123
    volumes:
      - mongo-db:/data/mongodb
  
  redis: 
    image: redis
    restart: always

volumes: 
  mongo-db:
    name: mongodb-data
