version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    ports: 
      - 80:80
  
  crud-node-app: 
    volumes:
      - ./:/app
      - /app/node_modules
      
    environment:
      - PORT=${PORT_PRODUCTION}
      - NODE_ENV=production

    command: npm run start
